### PR TITLE
Add laravel 11.x support

### PR DESCRIPTION
**Pull request by faytekin**

### CODE REVIEW

**Comment by ilhanaydinli** [comment]
Hello @mikebronner, we need Laravel 11 support, can we merge it quickly?

**Comment by epicentre** [comment]
@mikebronner can you merge this pr?

**Comment by nozdogan** [comment]
Hi @mikebronner , we are waiting this pr to upgrade our project to l11. Could you review it as soon as possible?

**Comment by mikebronner** [comment]
@faytekin thanks for the PR. I made the update separately from the PR.

**Pull request closed without merging**
